version: '3.9'

services:
  cs2kz-server:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "27015:27015/udp"
      - "27015:27015/tcp"
    volumes:
      # Replace ../cs2kz-metamod and ../server with whereever the repo and the server is
      - ../cs2kz-metamod:/cs2kz/cs2kz-metamod
      - ../server:/cs2kz/server
